/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InvoiceDTO {
  'customerName' : string,
  'total' : number,
  'customerPhone' : string,
  'date' : Time,
  'paid' : boolean,
  'invoiceNumber' : bigint,
  'customerAddress' : string,
  'items' : Array<InvoiceItem>,
  'subtotal' : number,
}
export interface InvoiceItem {
  'total' : number,
  'description' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'createInvoice' : ActorMethod<
    [string, string, string, Array<InvoiceItem>],
    bigint
  >,
  'getAllInvoices' : ActorMethod<[], Array<InvoiceDTO>>,
  'getInvoice' : ActorMethod<[bigint], InvoiceDTO>,
  'markAsPaid' : ActorMethod<[bigint], undefined>,
  'markAsUnpaid' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];