/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InvoiceItem = IDL.Record({
  'total' : IDL.Float64,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const Time = IDL.Int;
export const InvoiceDTO = IDL.Record({
  'customerName' : IDL.Text,
  'total' : IDL.Float64,
  'customerPhone' : IDL.Text,
  'date' : Time,
  'paid' : IDL.Bool,
  'invoiceNumber' : IDL.Nat,
  'customerAddress' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'subtotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createInvoice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(InvoiceItem)],
      [IDL.Nat],
      [],
    ),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(InvoiceDTO)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [InvoiceDTO], ['query']),
  'markAsPaid' : IDL.Func([IDL.Nat], [], []),
  'markAsUnpaid' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InvoiceItem = IDL.Record({
    'total' : IDL.Float64,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const Time = IDL.Int;
  const InvoiceDTO = IDL.Record({
    'customerName' : IDL.Text,
    'total' : IDL.Float64,
    'customerPhone' : IDL.Text,
    'date' : Time,
    'paid' : IDL.Bool,
    'invoiceNumber' : IDL.Nat,
    'customerAddress' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'subtotal' : IDL.Float64,
  });
  
  return IDL.Service({
    'createInvoice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(InvoiceItem)],
        [IDL.Nat],
        [],
      ),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(InvoiceDTO)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [InvoiceDTO], ['query']),
    'markAsPaid' : IDL.Func([IDL.Nat], [], []),
    'markAsUnpaid' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };